title: David Nadlinger
url: http://klickverbot.at
permalink: /blog/:year/:month/:title
source: src
destination: intermediate
plugins: plugins
pygments: true
paginate: 10
paginate_path: /blog/page/:num
